#!/bin/bash

clear
echo "Sauvegarde de Ghost"
sleep 3
echo "Archivage"
sleep 6
mv /home/docker/archives/docker

if [ -e /home/docker/archives/ghost5.tar ]
        then echo "ghost5.tar trouvé, supression" && sleep 3 && rm /home/docker/archives/ghost5.tar && echo "Ghost5 supprimé"
        else echo "ghost5.tar n'éxiste pas" && echo "Pas de suppression" && touch /home/docker/archives/ghost5.tar && echo "Ghost5 crée"
fi 
if [ -e /home/docker/archives/ghost4.tar ]
        then echo "ghost4.tar trouvé" 
        else echo "ghost4.tar n'éxiste pas" && touch /home/docker/archives/ghost4.tar && echo "Ghost4 crée"
fi 
if [ -e /home/docker/archives/ghost3.tar ]
        then echo "ghost3.tar trouvé" 
        else echo "ghost3.tar n'éxiste pas" && touch /home/docker/archives/ghost3.tar && echo "Ghost3 crée"
fi 
if [ -e /home/docker/archives/ghost2.tar ]
        then echo "ghost2.tar trouvé" 
        else echo "ghost2.tar n'éxiste pas" && touch /home/docker/archives/ghost2.tar && echo "Ghost2 crée"
fi 
if [ -e /home/docker/archives/ghostlastest.tar ]
        then echo "ghostlastest.tar trouvé"
        else echo "ghostlastest.tar n'éxiste pas" && touch /home/docker/archives/ghostlastest.tar && echo "ghostlastest.tar crée"
fi 
rm /home/docker/archives/ghost5.tar
mv /home/docker/archives/ghost4.tar /home/docker/archives/ghost5.tar
mv /home/docker/archives/ghost3.tar /home/docker/archives/ghost4.tar
mv /home/docker/archives/ghost2.tar /home/docker/archives/ghost3.tar
ms /home/docker/archives/ghostlastest /home/docker/archives/ghost2.tar
tar cvf /home/docker/archives/ghostlastest.tar /home/docker/ghost
